# .github/workflows/build-pacman-repo.yml

name: Build & Publish Pacman Repo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

permissions:
  contents: write

env:
  PKGBASE: linux-custom-test
  REPO_BRANCH: gh-pages

jobs:
  sync:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.latest }}
    steps:
      - uses: actions/checkout@v4

      - name: Fetch latest 6.12.x tag
        id: get_tag
        run: |
          latest=$(git ls-remote --tags --refs \
            https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git \
            | grep -E 'refs/tags/v6\.12\.[0-9]+$' \
            | sed 's|.*/v||' | sort -V | tail -1)
          echo "latest=$latest" >> $GITHUB_OUTPUT

      - name: Read current pkgver
        id: get_pkgver
        run: |
          current=$(grep '^pkgver=' PKGBUILD | cut -d= -f2)
          echo "current=$current" >> $GITHUB_OUTPUT

      - name: Bump pkgver & reset pkgrel
        if: ${{ steps.get_tag.outputs.latest != steps.get_pkgver.outputs.current }}
        run: |
          sed -i "s/^pkgver=.*/pkgver=${{ steps.get_tag.outputs.latest }}/" PKGBUILD
          sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD

      - name: Commit version bump
        if: ${{ steps.get_tag.outputs.latest != steps.get_pkgver.outputs.current }}
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci: bump to Linux v${{ steps.get_tag.outputs.latest }}"
          add: PKGBUILD

  build:
    needs: sync
    runs-on: ubuntu-latest
    container: archlinux:latest
    outputs:
      pkgver: ${{ steps.calc.outputs.pkgver }}
      pkgrel: ${{ steps.calc.outputs.pkgrel }}
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel bc cpio gettext git libelf pahole \
                              perl python tar xz pacman-contrib

      - name: Create builder user
        run: |
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          chown -R builder:builder $GITHUB_WORKSPACE

      - name: Build packages
        run: |
          sudo -u builder bash -lc "
            mkdir -p ~/build
            cp -r \$GITHUB_WORKSPACE/* ~/build/
            cd ~/build
            updpkgsums
            makepkg -s --noconfirm
            mkdir -p \$GITHUB_WORKSPACE/artifacts
            cp *.pkg.tar.zst \$GITHUB_WORKSPACE/artifacts/
          "

      - name: Compute new pkgrel
        id: calc
        run: |
          ver=$(grep '^pkgver=' PKGBUILD | cut -d= -f2)
          prev=$(git show HEAD~1:PKGBUILD | grep '^pkgver=' \
                   | cut -d= -f2 2>/dev/null || echo "")
          if [[ "$ver" != "$prev" ]]; then rel=1; else rel=$(( $(grep '^pkgrel=' PKGBUILD|cut -d= -f2)+1)); fi
          echo "pkgver=$ver" >> $GITHUB_OUTPUT
          echo "pkgrel=$rel">> $GITHUB_OUTPUT
          echo "$ver-$rel" > .tag

      - name: List & upload pkg artifacts
        run: ls -lh artifacts/
      - uses: actions/upload-artifact@v4
        with:
          name: pkgs
          path: artifacts/*.pkg.tar.zst

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (gh-pages)
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
          ref: ${{ env.REPO_BRANCH }}

      - name: Download built packages
        uses: actions/download-artifact@v4
        with:
          name: pkgs
          path: repo

      - name: Prepare repo dirs
        run: |
          mkdir -p repo/x86_64
          mv repo/*.pkg.tar.zst repo/x86_64/

      - name: Update pacman DB
        run: |
          cd repo
          repo-add ${PKGBASE}.db.tar.gz x86_64/*.pkg.tar.zst

      - name: Commit & push gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add repo/
          git commit -m "repo: add ${PKGBASE} v${{ needs.build.outputs.pkgver }}-r${{ needs.build.outputs.pkgrel }}"
          git push origin ${{ env.REPO_BRANCH }}
