name: Sync Linux 6.12 LTS Version

on:
  schedule:
    - cron:  '0 4 * * *'    # ogni giorno alle 04:00 UTC
  workflow_dispatch:       # esecuzione manuale

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest LTS 6.12.x tag
        id: upstream
        run: |
          latest=$(git ls-remote --tags --refs \
            https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git \
            | grep 'refs/tags/v6\.12\.[0-9]\+$' \
            | awk -F/ '{print $3}' \
            | sed 's/^v//' \
            | sort -V \
            | tail -1)
          echo "upstream_latest=$latest" >> $GITHUB_OUTPUT

      - name: Get current pkgver
        id: current
        run: |
          pv=$(grep '^pkgver=' PKGBUILD | cut -d= -f2)
          echo "current_pkgver=$pv" >> $GITHUB_OUTPUT

      - name: Debug values
        run: |
          echo "UPSTREAM  = ${{ steps.upstream.outputs.upstream_latest }}"
          echo "CURRENT   = ${{ steps.current.outputs.current_pkgver }}"

      - name: Bump pkgver & reset pkgrel
        if: ${{ steps.upstream.outputs.upstream_latest != steps.current.outputs.current_pkgver }}
        run: |
          echo "Syncing PKGBUILD: ${{ steps.current.outputs.current_pkgver }} → ${{ steps.upstream.outputs.upstream_latest }}"
          sed -i "s/^pkgver=.*/pkgver=${{ steps.upstream.outputs.upstream_latest }}/" PKGBUILD
          sed -i "s/^pkgrel=.*/pkgrel=1/" PKGBUILD

      - name: Commit & push changes
        if: ${{ steps.upstream.outputs.upstream_latest != steps.current.outputs.current_pkgver }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "ci: sync to Linux LTS ${{ steps.upstream.outputs.upstream_latest }}"
          add: PKGBUILD
          push: true
          default_author: false
